ROOT_FOLDER = '/Users/shawnkaku/repositories/mirlab/foxconn/demo-web/'
STATIC_FOLDER = ROOT_FOLDER + '/static/'
UPLOAD_FOLDER = ROOT_FOLDER + '/static/uploads'
RUN_FOLDER = '/home/kaldi/foxconn-asr/decode_demo'
DEMO_FOLDER = '/home/kaldi/foxconn-asr/decode_demo/local/demo'
