ROOT_FOLDER = '/home/kaldi/MIR-asr/web_demo'
STATIC_FOLDER = '/home/kaldi/MIR-asr/web_demo/static'
UPLOAD_FOLDER = '/home/kaldi/MIR-asr/web_demo/static/uploads'
RUN_FOLDER = '/home/kaldi/MIR-asr/decode_demo'
DEMO_FOLDER = '/home/kaldi/MIR-asr/decode_demo/local/demo'